config/routes.rb
Sndcrd::Application.routes.draw do

  resources :cards

  
  root to: 'cards#index'
  get '/cards/get_tracks/:id', to: 'cards#get_tracks', as: 'card_get_tracks'
  get '/cards/get_images/:id', to: 'cards#get_images', as: 'card_get_images'
  get '/cards/send_email/:id', to: 'cards#send_email', as: 'card_send_email'
  get 'cards/:id/display' => 'cards#display', as: :display
  get 'cards/:id/dancer_visualise' => 'cards#dancer_visualise', as: :dancer_visualise
  get 'cards/:id/succes' => 'cards#succes', as: :succes

end

app/models/card.rb
class Card < ActiveRecord::Base
	validates_presence_of :name
	validates_presence_of :tag
	validates_presence_of :message


	def get_tracks(tags='birthday')
	  # create client object with app credentials
	  client = Soundcloud.new(:client_id => SECRETS['soundcloud']['client_id'],
	  	                      :client_secret => SECRETS['soundcloud']['client_secret'],
	  	                      :redirect_uri => 'localhost')

	  tag_array = tags.split(",")
	  first_tag = tag_array[0]

	  tracks = client.get('/tracks', :q=>first_tag)
	  random_track = rand(tracks.length)
	  track = tracks.at(random_track)
	  embed_info = client.get('/oembed', :url => track.permalink_url)
	  self.sound = embed_info['html']
	  self.track_id = track.id
	end


	def get_images(tags='birthdaycake, geburtstagskind, baloons')
		EyeEmConnector.configure do |config|
			config.client_id     = SECRETS['eyeem']['client_id']
			config.client_secret = SECRETS['eyeem']['client_secret']
			config.access_token  = SECRETS['eyeem']['access_token']
		end

		items = []
		tag_array = tags.split(",")
		tag_array.each do |query|
			query.strip!
			results = EyeEmConnector.get('search', {:q=>query, :includeAlbums=>1, :limit=>50})
			b = results.env[:body]
			a = b["albums"]
			i = a["items"]
			items.concat(i)
		end

		sorted = items.sort_by {|likes| likes["totalLikers"] }
		nr = 30
		if sorted.length < 30
			nr = sorted.length
		end
		random_image = rand(nr)
		item = sorted.at(sorted.length - random_image)
		array = item["thumbUrl"].split("/200/")

		new_string = array[0] + "/500/" + array[1]
		self.image = new_string
	end

  	def send_email(r_email, title, card_id)
    	Mailjet.configure do |config|
    		config.api_key      = SECRETS['mailjet']['api_key']
      		config.secret_key   = SECRETS['mailjet']['secret_key']
      		config.default_from = 'george_clooney@bgcodehack.com'
    	end
    list = Mailjet::List.all.find{|l| l.id == "437219" }
    list.add_contacts(r_email, force: true)
    campaign = Mailjet::Campaign.create(title: title, list_id: list.id, from: "olamad@gmail.com", subject: "You got WOW!ed", lang: "en", footer: "default", from_name: "George Clooney")
    campaign.set_html("<html><head><title>WoW!</title></head><body><h1>You just got WOW!ed</h1><p><a href=\"http://localhost:3000/cards/#{card_id}/display\">Check your WOW!</a></p><br> <a href=\"[[UNSUB_LINK_EN]]\">[[UNSUB_LINK_EN]]</a></body></html>") 
	campaign.send!
	list.unsubscribe_contact(r_email)
  end

end

app/models/theme.rb
class Theme < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  def dancer_visualise
    @card = Card.find(params[:id])
    render layout: false
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    @card.get_tracks(card_params[:tag])
    @card.get_images(card_params[:tag])

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render action: 'show', status: :created, location: @card }
      else
        format.html { render action: 'new' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def display
     @card = Card.find(params[:id])
  end

  def succes
     @card = Card.find(params[:id])
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end

  def get_tracks
    @card = Card.find(params[:id])
    @card.get_tracks(@card.tag)
    @card.save!
    redirect_to request.referer
  end

  def get_images
    @card = Card.find(params[:id])
    @card.get_images(@card.tag)
    @card.save!
    redirect_to request.referer
  end

  def send_email
    @card = Card.find(params[:id])
    @card.send_email(@card.r_email, @card.name, @card.id)
    redirect_to succes_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:name, :tag, :message, :image, :sound, :r_email, :r_name, :track_id)
    end
end

app/controllers/theme_controller.rb
class ThemeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/theme_helper.rb
module ThemeHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <h2>Who are you going to WOW?</h2>
  <div class="field">
    <%= f.label 'Name' %><br />
    <%= f.text_field :r_name %>
  </div>
  <div class="field">
    <%= f.label 'Email' %><br />
    <%= f.text_field :r_email %>
  </div>

  <h2>WOW Details</h2>
  <div class="field">
    <%= f.label 'Title' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label 'What should you WOW! be about?' %><br />
    <%= f.text_field :tag, :value => 'berlin, geekette' %>
  </div>
  <div class="hidden">
    <div class="field">
      <%= f.label :image %><br />
      <%= f.text_field :image, :value => 'http://www.eyeem.com/thumb/sq/500/67be5509b0aa0322913775cf99ea6604f27a437c-1347052741' %>
    </div>
    <div class="field">
      <%= f.label :sound %><br />
      <%= f.text_field :sound %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Next', :class => 'bigButton clickable' %>
  </div>
<% end %>

app/views/cards/dancer_visualise.html.erb
<!DOCTYPE html>
<html>
	<head>
		<link href='/assets/dancer.css' rel='stylesheet' type='text/css'>
	</head>
	<body data-track-id="<%= @card.track_id %>">
		<!-- Demo dependencies -->
		<script src="/assets/dancerjs/Three.js"></script>
		<script src="/assets/dancerjs/Stats.js"></script>
		<script src="/assets/dancerjs/Detector.js"></script>

		<!-- Dancer.js -->
		<script src="/assets/dancerjs/dancer.js"></script>

		<!-- Demo stuff -->
		<script src="/assets/dancerjs/scene.js"></script>
		<script src="/assets/dancerjs/player.js"></script>
	</body>

</html>

app/views/cards/display.html.erb
  <div class="box">
<div class="box">
  <div class="title" id="cardTitle"><%= @card.name %></div>
  <div id="cardImage">
    <%= image_tag(@card.image, :class => "cardImage" ) if @card.image.present?%>
    
  </div>
  <div id="cardControls">
    <div class="center">
      <!-- <span class="iconButton play"></span> -->
      <span class="iconButton pause"></span>
      <span class="iconButton mute last"></span>
    </div>
    <div class="clear"></div>
  </div>
  <div id="cardDetails">
    <div id="cardMessage">
      <%= @card.message %>
    </div>
    <div id="properties">
      WOW! from <span id="senderName" class="details">George Clooney</span> sent <span id="cardDate" class="">today</span>! 
    </div>
  </div>
</div>

<iframe src="<%= dancer_visualise_path %>" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; z-index: -1"></iframe>
</div>

app/views/cards/edit.html.erb
<div class="box">
<h1 class="demo-headline">Edit</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>
</div>

app/views/cards/index.html.erb
  <div class="box">
<div class="addBox clear">
  <%= link_to 'Create WOW!', new_card_path, :class => "bigButton clickable" %>
</div>

<!-- <a id="toggleCardHistory" href="#">Toggle Card History</a> -->

<div id="cardHistory">
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Tag</th>
        <th class="narrow"></th>
        <th class="narrow"></th>
        <th class="narrow"></th>
      </tr>
    </thead>

    <tbody>
      <% @cards.each do |card| %>
      <tr>
        <td><%= card.name %></td>
        <td><%= card.tag %></td>
        <td><%= link_to 'Show', card, :class => "smallButton clickable" %></td>
        <td><%= link_to 'Edit', edit_card_path(card),:class => "smallButton clickable" %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' }, :class => "smallButton clickable" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br />
</div>

app/views/cards/new.html.erb
<div class="box">
<!-- <h1 class="demo-headline">Create your WOW!</h1> -->
<%= render 'form' %>
</div>

app/views/cards/show.html.erb
<div class="box">

<div class="block">
  <h2>You are WOWing</h2>
  <p>
    <%= @card.r_name %>
    <%= @card.r_email %>
  </p>
</div>

<div class="block">
  <h2><%= @card.name %></h2>
  
  <p>
    <%= @card.message %>
  </p>

  <p>
    <strong>Based on these tags:</strong>
    <%= @card.tag %>
  </p>

  <div><%= image_tag(@card.image , :class => 'smallImage') if @card.image.present? %></div>
  <%= link_to 'Get me a different image', card_get_images_path(@card), :class => "smallButton clickable" %>

  <div><%= @card.sound.html_safe %></div>
  <%= link_to 'Get me a different track', card_get_tracks_path(@card), :class => "smallButton clickable" %>
</div>

<%= link_to 'Send this WOW!', card_send_email_path(@card), :class => "bigButton clickable" %>

</div>

app/views/cards/succes.html.erb
<div class="box">
<h1>Your WOW!Card is now on the way!</h1>

<%= link_to 'Show me my finished WOW!',  display_path, :class => "bigButton clickable" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>WOW!Card</title>
	<link rel="shortcut icon" type="image/png" href="/assets/favico.png">
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div id="header">
		<%= link_to '', cards_path, :id => 'logo' %>
	</div>
	<%= yield %>
</body>
</html>